//! M0 config schema for `runsible-pull` (`pull.toml`).
//!
//! Per the runsible-pull plan §10, M0 supports only the local pull, unsigned,
//! one-shot story. This is a curated subset of the §4 schema: only `[source]`,
//! `[apply]`, and `[paths]`. Later milestones add `[schedule]`, `[heartbeat.http]`,
//! `[verify]`, `[isolation]`, etc.
//!
//! Path values may begin with `~/` and are expanded against `$HOME`.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::errors::{PullError, Result};

/// Top-level `pull.toml` schema (M0 subset).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PullConfig {
    pub source: SourceConfig,
    pub apply: ApplyConfig,
    pub paths: PathsConfig,
}

/// `[source]` table — where to fetch the bundle from.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SourceConfig {
    /// M0: only `"git"`.
    pub kind: String,

    /// HTTPS URL, file:// URL, or SSH-style (M0 stubs SSH).
    pub url: String,

    /// Branch to track. Defaults to `"main"`.
    #[serde(default = "default_branch")]
    pub branch: String,

    /// Optional SSH key path. M0 stubs to "not implemented".
    #[serde(default)]
    pub ssh_key: Option<PathBuf>,
}

fn default_branch() -> String {
    "main".into()
}

/// `[apply]` table — what to run once the bundle is on disk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ApplyConfig {
    /// Path to the playbook within the fetched bundle.
    pub playbook: PathBuf,

    /// M0: empty / ignored. Reserved for `--extra-vars` style passthrough.
    #[serde(default)]
    pub extra_vars: Vec<String>,
}

/// `[paths]` table — local on-disk state.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PathsConfig {
    /// Directory where bundle, lock, and heartbeat live.
    pub state_dir: PathBuf,

    /// Where the heartbeat JSON is written. Usually `<state_dir>/heartbeat.json`.
    pub heartbeat_path: PathBuf,
}

impl PullConfig {
    /// Parse a `pull.toml` body and expand any `~/` path prefixes against `$HOME`.
    pub fn from_str(body: &str) -> Result<Self> {
        let raw: PullConfig = toml::from_str(body).map_err(|e| PullError::InvalidConfigToml {
            path: PathBuf::from("<inline>"),
            source: e,
        })?;
        raw.expanded()
    }

    /// Read a `pull.toml` from disk, expanding `~/` paths.
    pub fn load(path: &Path) -> Result<Self> {
        let body = std::fs::read_to_string(path)?;
        let raw: PullConfig = toml::from_str(&body).map_err(|e| PullError::InvalidConfigToml {
            path: path.to_path_buf(),
            source: e,
        })?;
        raw.expanded()
    }

    /// Return a copy with all path-shaped fields expanded.
    pub fn expanded(self) -> Result<Self> {
        let mut cfg = self;
        cfg.paths.state_dir = expand_home(&cfg.paths.state_dir)?;
        cfg.paths.heartbeat_path = expand_home(&cfg.paths.heartbeat_path)?;
        cfg.apply.playbook = cfg.apply.playbook.clone(); // playbook is bundle-relative
        if let Some(k) = cfg.source.ssh_key.as_ref() {
            cfg.source.ssh_key = Some(expand_home(k)?);
        }
        Ok(cfg)
    }

    /// Validate M0 invariants (source kind, etc.). Returns the (unchanged) config.
    pub fn validate(&self) -> Result<()> {
        if self.source.kind != "git" {
            return Err(PullError::UnsupportedSourceKind(self.source.kind.clone()));
        }
        Ok(())
    }
}

/// Expand a leading `~/` (or bare `~`) against `$HOME` / `dirs::home_dir()`.
///
/// Other path forms are returned unchanged. This is intentionally narrow: only
/// the `~/` prefix is expanded. Inline `~user` lookups are not supported at M0.
pub fn expand_home(p: &Path) -> Result<PathBuf> {
    let s = match p.to_str() {
        Some(s) => s,
        None => return Ok(p.to_path_buf()),
    };
    if s == "~" {
        let home = home_dir(s)?;
        return Ok(home);
    }
    if let Some(rest) = s.strip_prefix("~/") {
        let mut home = home_dir(s)?;
        home.push(rest);
        return Ok(home);
    }
    Ok(p.to_path_buf())
}

fn home_dir(original: &str) -> Result<PathBuf> {
    if let Ok(h) = std::env::var("HOME") {
        if !h.is_empty() {
            return Ok(PathBuf::from(h));
        }
    }
    dirs::home_dir().ok_or_else(|| PullError::HomeUnresolved(original.to_string()))
}

/// A starter `pull.toml` rendered as a string. Used by `runsible-pull init`.
pub fn init_default() -> String {
    let stub = r#"# pull.toml — generated by `runsible-pull init`
# M0 subset: local pull, unsigned, one-shot.

[source]
kind = "git"
url = "https://example.com/ops/site.git"
branch = "main"
# ssh_key = "~/.ssh/id_ed25519"

[apply]
playbook = "playbooks/site.toml"
extra_vars = []

[paths]
state_dir = "~/.local/state/runsible-pull"
heartbeat_path = "~/.local/state/runsible-pull/heartbeat.json"
"#;
    stub.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_parse_minimal() {
        let body = r#"
[source]
kind = "git"
url = "https://example.com/ops/site.git"

[apply]
playbook = "playbooks/site.toml"

[paths]
state_dir = "/var/lib/rp"
heartbeat_path = "/var/lib/rp/heartbeat.json"
"#;
        let cfg = PullConfig::from_str(body).expect("parse");
        assert_eq!(cfg.source.url, "https://example.com/ops/site.git");
        assert_eq!(cfg.source.branch, "main");
        assert_eq!(cfg.apply.playbook, PathBuf::from("playbooks/site.toml"));
        assert!(cfg.apply.extra_vars.is_empty());
        assert!(cfg.source.ssh_key.is_none());
        cfg.validate().unwrap();
    }

    #[test]
    fn home_expansion() {
        // Force a known HOME for the duration of this test.
        let prev = std::env::var("HOME").ok();
        std::env::set_var("HOME", "/tmp/fake-home");

        let body = r#"
[source]
kind = "git"
url = "https://example.com/ops/site.git"

[apply]
playbook = "playbooks/site.toml"

[paths]
state_dir = "~/.local/state/runsible-pull"
heartbeat_path = "~/.local/state/runsible-pull/heartbeat.json"
"#;
        let cfg = PullConfig::from_str(body).expect("parse");

        if let Some(p) = prev {
            std::env::set_var("HOME", p);
        } else {
            std::env::remove_var("HOME");
        }

        assert_eq!(
            cfg.paths.state_dir,
            PathBuf::from("/tmp/fake-home/.local/state/runsible-pull")
        );
        assert_eq!(
            cfg.paths.heartbeat_path,
            PathBuf::from("/tmp/fake-home/.local/state/runsible-pull/heartbeat.json")
        );
    }

    #[test]
    fn init_default_is_valid_toml() {
        let s = init_default();
        let cfg = PullConfig::from_str(&s).expect("init_default parses");
        assert_eq!(cfg.source.kind, "git");
    }

    #[test]
    fn rejects_non_git_source_kind() {
        let body = r#"
[source]
kind = "s3"
url = "s3://bucket/key"

[apply]
playbook = "site.toml"

[paths]
state_dir = "/tmp/rp"
heartbeat_path = "/tmp/rp/heartbeat.json"
"#;
        let cfg = PullConfig::from_str(body).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(matches!(err, PullError::UnsupportedSourceKind(_)));
    }
}
