use std::fs;
use std::path::Path;

use crate::errors::Result;
use crate::manifest::{scaffold_manifest, write_manifest_file};

/// Create a new package directory at `base/<name>/` with a scaffold manifest
/// and empty skeleton files.
pub fn init_package(name: &str, base: Option<&Path>) -> Result<()> {
    let base = base.unwrap_or_else(|| Path::new("."));
    let pkg_dir = base.join(name);
    fs::create_dir_all(&pkg_dir)?;

    let manifest = scaffold_manifest(name);
    let manifest_path = pkg_dir.join("runsible.toml");
    write_manifest_file(&manifest_path, &manifest)?;

    for sub in &["tasks", "handlers", "defaults"] {
        let dir = pkg_dir.join(sub);
        fs::create_dir_all(&dir)?;
        fs::write(
            dir.join("main.toml"),
            b"# auto-generated by runsible-galaxy init\n",
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::parse_manifest_file;

    #[test]
    fn init_creates_manifest() {
        let tmp = std::env::temp_dir()
            .join(format!("runsible-init-test-{}", std::process::id()));
        fs::create_dir_all(&tmp).unwrap();

        init_package("testpkg", Some(&tmp)).unwrap();

        let manifest_path = tmp.join("testpkg").join("runsible.toml");
        assert!(manifest_path.exists(), "runsible.toml should be created");

        let m = parse_manifest_file(&manifest_path).unwrap();
        assert_eq!(m.package.name, "testpkg");

        let _ = fs::remove_dir_all(&tmp);
    }
}
